In [5]:
import pandas as pd
import numpy as np
from os import cpu_count
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier 

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis


In [21]:
from utils import load_data
data = load_data()
pd.factorize(data['increase_stock'])

(array([0, 0, 0, ..., 0, 1, 0], dtype=int64), Index([0, 1], dtype='int64'))

# initialize_model_pipeline handles all the preprocessing
## (visualize the pipeline by hanging the variable at the end of the cell)

In [30]:
from utils import initialize_model_pipeline
model = initialize_model_pipeline(LogisticRegression(random_state=123, max_iter=10000))
model

Pipeline(steps=[('pre',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  ['hour_of_day', 'month']),
                                                 ('gen', Generator(),
                                                  ['hour_of_day']),
                                                 ('bin', 'passthrough',
                                                  ['weekday', 'summertime']),
                                                 ('weather',
                                                  WeatherTransformer(),
                                                  ['summertime', 'temp', 'dew',
                                                   'humidity', 'precip',
                                                   'snowdepth', 'windspeed',
                                                   'cloudcover',
                                                   'visibility'])])),
                ('model',
                 LogisticRegression(max_iter=10000, random_state=123))])

## Call fit just like you would any other model

In [31]:
model.fit(data.drop('increase_stock',axis=1), data['increase_stock'])
model.score(X=data, y=data['increase_stock'])

c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dt

0.89875

### Since everything is in the pipeline, this means that you can even pass in just the original data and it will process it the same way every time (for the X variables)
#### note: this also means you dont get to choose features anymore

In [32]:
model.fit(X=data, y=data['increase_stock'])
model.predict(data)

c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dt

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [33]:
model[:-1].get_feature_names_out()

array(['cat__hour_of_day_0', 'cat__hour_of_day_1', 'cat__hour_of_day_2',
       'cat__hour_of_day_3', 'cat__hour_of_day_4', 'cat__hour_of_day_5',
       'cat__hour_of_day_6', 'cat__hour_of_day_7', 'cat__hour_of_day_8',
       'cat__hour_of_day_9', 'cat__hour_of_day_10', 'cat__hour_of_day_11',
       'cat__hour_of_day_12', 'cat__hour_of_day_13',
       'cat__hour_of_day_14', 'cat__hour_of_day_15',
       'cat__hour_of_day_16', 'cat__hour_of_day_17',
       'cat__hour_of_day_18', 'cat__hour_of_day_19',
       'cat__hour_of_day_20', 'cat__hour_of_day_21',
       'cat__hour_of_day_22', 'cat__hour_of_day_23', 'cat__month_1',
       'cat__month_2', 'cat__month_3', 'cat__month_4', 'cat__month_5',
       'cat__month_6', 'cat__month_7', 'cat__month_8', 'cat__month_9',
       'cat__month_10', 'cat__month_11', 'cat__month_12', 'gen__daytime',
       'gen__rushhour', 'bin__weekday', 'bin__summertime',
       'weather__score'], dtype=object)

## Super easy. Now just change the model as you please

In [60]:
from sklearn.metrics import classification_report
model_reg = initialize_model_pipeline(LinearRegression())
model_tree = initialize_model_pipeline(RandomForestClassifier(n_jobs=cpu_count()))
model_lda = initialize_model_pipeline(LinearDiscriminantAnalysis())
model_qda = initialize_model_pipeline(QuadraticDiscriminantAnalysis())
model_qda[0]

AttributeError: 'ColumnTransformer' object has no attribute 'transformers_'

In [53]:
from sklearn.metrics import classification_report
model_reg = initialize_model_pipeline(LinearRegression())
model_tree = initialize_model_pipeline(RandomForestClassifier(n_jobs=cpu_count()))
model_lda = initialize_model_pipeline(LinearDiscriminantAnalysis())
model_qda = initialize_model_pipeline(QuadraticDiscriminantAnalysis())
model_reg.fit(data, data['increase_stock'])
model_tree.fit(data, data['increase_stock'])
model_lda.fit(data, data['increase_stock'])
model_qda.fit(data, data['increase_stock'])

print(f'Lin. Reg. Score:')
print(classification_report(data['increase_stock'],np.round(model_reg.predict(data)).astype(int)))
print(f'Trees Score:')
print(classification_report(data['increase_stock'], model_tree.predict(data)))
print(f'LDA Score:')
print(classification_report(data['increase_stock'], model_lda.predict(data)))
print(f'QDA Score:')
print(classification_report(data['increase_stock'], model_qda.predict(data)))

c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dt

TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.

### Want to run K folds?? Just use the utils function

In [56]:
from utils import cross_validate_model
cross_validate_model(model_tree, data, data['increase_stock'])

c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Ellaa\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dt

array([0.865625, 0.871875, 0.8375  , 0.909375, 0.86875 ])

#### Want to run it with more folds?

In [22]:
leave_out_one = cross_validate_model(model_tree, data, data['increase_stock'],n_splits=len(data))

In [23]:
np.mean(leave_out_one)

0.87

#### Want to bootstrap your coefficients?
##### use the bootstrap_model function and get all the ranges of your coefficients (average them to bag)D